# Enable or disable features
# true = enabled
# false = disabled

# Close Inventory by clicking outside
close-inv: true

# Rotate redstone comparators and repeaters with sneak + right click
rotate-redstone: true

# Break trees faster (Timber)
timber: true

# Grow vines
grow-vines: true

# Change shaped crafting recipe to shapeless
shapeless-bread: true
shapeless-books: true

# Furnace recipes
flesh-to-leather: true

# Custom crafting recipes
stairs-to-blocks: true
slabs-to-blocks: true
flint-to-gravel: true
wool-to-string: true
dropper-to-dispenser: true

dropper-to-dispenser-shaped: true
dropper-to-dispenser-pattern:
  - " IS"
  - "IXS"
  - " IS"
# I = Stick
# S = String
# X = Dropper

# Uncraftable items made craftable
horse-armor: true
horse-armor-pattern:
  - "  O"
  - "OOO"
  - "OXO"
# O = diamond, gold or iron
# X = saddle

saddle: true
saddle-pattern:
  - "  O"
  - "OOO"
  - "O O"
# O = leather

nametag: true
nametag-pattern:
  - "  S"
  - " P "
  - "P  "
# S = string
# P = paper